name: pvd
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pytorch=1.4.0
  - cudatoolkit=10.1
  - matplotlib=2.2.5
  - tqdm=4.32.1
  - scipy=1.5.1
  - pip
  - pip:
      - torchvision==0.5.0
      - open3d==0.9.0
      - trimesh==3.7.12